### ISSUE TITLE
Random sampling problem

### ISSUE THREAD

**Issue by huilin-al** [chloroExtractorTeam/benchmark#60]
Hello, I have some problems when using seqkit random sampling. It may be because my file is too large. Please refer to your command for details: seqkit sample --threads 8 --rand-seed 91685 --number 2000000 --out-file ${BASE}.2M.fq $i
Is there any tool or script that can replace seqkit random sampling?

**Comment by greatfireball** [comment]
Dear huilin-al,

finally, it depends on your input data. Do you know the number of reads? Are the reads paired end reads? Do your require exactly 2 million reads(read pairs). Normally, the random sampling should not time critical, especially, if you only need to subsample one library.

Best,
Frank

**Comment by huilin-al** [comment]
Hello, I am also a simulated paired-end sequencing, mine is 3 million reads (read pairs). It is possible that the depth of my simulated gene is too high, resulting in a large input data. It took me two days to find a solution. Thank you very much!

**Comment by greatfireball** [comment]
Thus, your problem is solved?

**Comment by huilin-al** [comment]
Yes thank you very much！Another sampling tool I use
