### ISSUE TITLE
Small questions about assembly

### ISSUE THREAD

**Issue by huilin-al** [chloroExtractorTeam/benchmark#61]
I want to ask whether the simulated data should be separately proposed for chloroplasts and then assembled. I have a disagreement. I don’t know which way to go. My professor thinks that the simulated data can extract the organelle genes I want Come out and assemble it again. I will try it with GetOrganelle. It is not the result I want, or I should use other tools to extract the organelle genes I want and assemble it.

**Comment by iimog** [comment]
I'm afraid I don't quite understand your question. What exactly are you trying to achieve? How do you currently do it? What is the expected and what the observed result?

**Comment by huilin-al** [comment]
Sorry, I have been growing materials for some time recently, so there is no time to reply to you.I want to imitate your article "A systematic comparison of chloroplast genome assembly tools" to compare which tool is suitable for assembling the mitochondrial genome, but I have a problem now. I use a simulation tool to simulate the sequenced mitochondrial genome, plus the genome And the chloroplast genome, I should extract the 3M genome after combining the genes, but I found that the next result is not what I want, so I am thinking about how to adjust my direction.

**Comment by iimog** [comment]
Sounds interesting! I hope this repository can serve as a blueprint of doing the benchmark for mitochondria tools. Hope you can fix your issue. If you have an idea about how we can help or a concrete question feel free to open another issue. Best of luck for your project!

**Comment by huilin-al** [comment]
ok, thank you very much!
